name: CI with Caching

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-with-cache:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Create a folder to simulate dependencies
      - name: Create directory for caching
        run: mkdir -p dummy_dependencies

      # Step 3: Cache the dependencies
      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: dummy_dependencies
          key: cache-cfe919e

      # Step 4: Echo whether cache was hit or missed
      - name: prime-cache-cfe919e
        run: |
          echo "The cache-hit property was: ${{ steps.cache-step.outputs.cache-hit }}"


